platform :ios, '9.0'
inhibit_all_warnings!

target 'einkaufsapp' do
  pod 'ObjectiveSugar', '~> 0.5'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end